// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChatMessage is the predicate function for chatmessage builders.
type ChatMessage func(*sql.Selector)

// ChatRoom is the predicate function for chatroom builders.
type ChatRoom func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
